#!/bin/sh

TERM=xterm

NOCOL='\e[0m'    # Text Reset
GREEN='\e[0;32m'
RED='\e[0;31m';

if [[ -d "$HOME/.daml" ]]
then
    echo "${GREEN}daml already installed...${NOCOL}"
else
    echo -e "${GREEN}Installing daml....${NOCOL}"
    curl -sSL https://get.daml.com/ | /bin/sh 
fi

emacs
